20180329

diff --git a/bin/sparky-desktop b/bin/sparky-desktop
--- a/bin/sparky-desktop
+++ b/bin/sparky-desktop
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# last update 2018/03/18 by pavroo
+# last update 2018/03/29 by pavroo
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-desktop"
@@ -56,11 +56,12 @@ else
 	USER1002="$CHECKUSER1002"
 fi
 
-if [ -f /usr/bin/sparky-terminal ]
+if [ -f /usr/bin/sparky-xterm ]
 then
-	SPARKYXTERM="sparky-terminal"
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 ARCHARM="`uname -m | grep arm`"
 
@@ -210,9 +211,9 @@ then
 		$DIALOG $TEXT"\n$LOCAL14" $TITLE"$LOCAL6" $OKBUTTON
 		exit 1
 	else
-		$SPARKYXTERM -e "apt-get update"
-		$SPARKYXTERM -e "apt-get install --no-install-recommends sparky-desktop-$PACKAGE && apt-get install -f"
-		#$SPARKYXTERM -e "apt-get install -f"
+		$SPARKYXTERM "apt-get update"
+		$SPARKYXTERM "apt-get install --no-install-recommends sparky-desktop-$PACKAGE"
+		$SPARKYXTERM "apt-get install -f"
 	fi
 
 elif [ "$1" = "budgie" ]
@@ -222,9 +223,9 @@ then
 		$DIALOG $TEXT"\n$LOCAL14" $TITLE"$LOCAL6" $OKBUTTON
 		exit 1
 	else
-		$SPARKYXTERM -e "apt-get update"
-		$SPARKYXTERM -e "apt-get install --no-install-recommends sparky-desktop-$PACKAGE && apt-get install -f"
-		#$SPARKYXTERM -e "apt-get install -f"
+		$SPARKYXTERM "apt-get update"
+		$SPARKYXTERM "apt-get install --no-install-recommends sparky-desktop-$PACKAGE"
+		$SPARKYXTERM "apt-get install -f"
 	fi
 
 elif [ "$1" = "cde" ]
@@ -234,9 +235,9 @@ then
 		$DIALOG $TEXT"\n$LOCAL14" $TITLE"$LOCAL6" $OKBUTTON
 		exit 1
 	else
-		$SPARKYXTERM -e "apt-get update"
-		$SPARKYXTERM -e "apt-get install sparky-desktop-$PACKAGE && apt-get install -f"
-		#$SPARKYXTERM -e "apt-get install -f"
+		$SPARKYXTERM "apt-get update"
+		$SPARKYXTERM "apt-get install sparky-desktop-$PACKAGE"
+		$SPARKYXTERM "apt-get install -f"
 	fi
 
 #elif [ "$1" = "deepin" ]
@@ -256,9 +257,9 @@ then
 #		fi
 #		echo "deb https://sparkylinux.org/repo/ dde main" > /etc/apt/sources.list.d/sparky-dde.list
 #		echo "deb-src https://sparkylinux.org/repo/ dde main" >> /etc/apt/sources.list.d/sparky-dde.list
-#		$SPARKYXTERM -e "apt-get update"
-#		$SPARKYXTERM -e "apt-get install --no-install-recommends sparky-desktop-$PACKAGE -y"
-#		$SPARKYXTERM -e "apt-get install -f"
+#		$SPARKYXTERM "apt-get update"
+#		$SPARKYXTERM "apt-get install --no-install-recommends sparky-desktop-$PACKAGE -y"
+#		$SPARKYXTERM "apt-get install -f"
 #	fi
 
 elif [ "$1" = "enlightenment" ]
@@ -268,9 +269,9 @@ then
 		$DIALOG $TEXT"\n$LOCAL14" $TITLE"$LOCAL6" $OKBUTTON
 		exit 1
 	else
-		$SPARKYXTERM -e "apt-get update"
-		$SPARKYXTERM -e "apt-get install --no-install-recommends sparky-desktop-$PACKAGE && apt-get install -f"
-		#$SPARKYXTERM -e "apt-get install -f"
+		$SPARKYXTERM "apt-get update"
+		$SPARKYXTERM "apt-get install --no-install-recommends sparky-desktop-$PACKAGE"
+		$SPARKYXTERM "apt-get install -f"
 	fi
 
 elif [ "$1" = "pantheon" ]
@@ -292,10 +293,10 @@ then
 			rm -f /etc/apt/sources.list.d/pantheon-debian.list
 		fi
 		echo "deb http://gandalfn.ovh/debian testing-daily main contrib" > /etc/apt/sources.list.d/pantheon-debian.list
-		$SPARKYXTERM -e "wget http://gandalfn.ovh/debian/pantheon-debian.gpg.key -O- | apt-key add -"
-		$SPARKYXTERM -e "apt-get update"
-		$SPARKYXTERM -e "apt-get install sparky-desktop-$PACKAGE && apt-get install -f"
-		#$SPARKYXTERM -e "apt-get install -f"
+		$SPARKYXTERM "wget http://gandalfn.ovh/debian/pantheon-debian.gpg.key -O- | apt-key add -"
+		$SPARKYXTERM "apt-get update"
+		$SPARKYXTERM "apt-get install sparky-desktop-$PACKAGE"
+		$SPARKYXTERM "apt-get install -f"
 	elif [ "$SPARKYVERCHECK4" != "" ] || [ "$DEBIANVERCHECK9" != "" ]
 	then
 		if [ -f /etc/apt/sources.list.d/pantheon-debian.list ]
@@ -303,10 +304,10 @@ then
 			rm -f /etc/apt/sources.list.d/pantheon-debian.list
 		fi
 		echo "deb http://gandalfn.ovh/debian stretch-loki main contrib" > /etc/apt/sources.list.d/pantheon-debian.list
-		$SPARKYXTERM -e "wget http://gandalfn.ovh/debian/pantheon-debian.gpg.key -O- | apt-key add -"
-		$SPARKYXTERM -e "apt-get update"
-		$SPARKYXTERM -e "apt-get install sparky-desktop-$PACKAGE && apt-get install -f"
-		#$SPARKYXTERM -e "apt-get install -f"
+		$SPARKYXTERM "wget http://gandalfn.ovh/debian/pantheon-debian.gpg.key -O- | apt-key add -"
+		$SPARKYXTERM "apt-get update"
+		$SPARKYXTERM "apt-get install sparky-desktop-$PACKAGE"
+		$SPARKYXTERM "apt-get install -f"
 	fi
 
 elif [ "$1" = "trinity" ]
@@ -319,29 +320,29 @@ then
 
 	if [ "$OLDSTABLECHECK1" != "" ] || [ "$OLDSTABLECHECK2" != "" ]
 	then
-		$SPARKYXTERM -e "apt-key adv --keyserver keyserver.quickbuild.pearsoncomputing.net --recv-keys F5CFC95C"
+		$SPARKYXTERM "apt-key adv --keyserver keyserver.quickbuild.pearsoncomputing.net --recv-keys F5CFC95C"
 		echo "deb http://mirror.ppa.trinitydesktop.org/trinity/trinity-r14.0.0/debian jessie main" >> /etc/apt/sources.list.d/trinity.list
 		echo "deb-src http://mirror.ppa.trinitydesktop.org/trinity/trinity-r14.0.0/debian jessie main" >> /etc/apt/sources.list.d/trinity.list
 		echo "deb http://mirror.ppa.trinitydesktop.org/trinity/trinity-builddeps-r14.0.0/debian jessie main" >> /etc/apt/sources.list.d/trinity.list
 		echo "deb-src http://mirror.ppa.trinitydesktop.org/trinity/trinity-builddeps-r14.0.0/debian jessie main" >> /etc/apt/sources.list.d/trinity.list
 	elif [ "$SPARKYVERCHECK5" != "" ] || [ "$DEBIANVERCHECK10" != "" ]
 	then
-		$SPARKYXTERM -e "apt-key adv --keyserver keys.gnupg.net --recv-key A04BE668"
+		$SPARKYXTERM "apt-key adv --keyserver keys.gnupg.net --recv-key A04BE668"
 		echo "deb http://mirror.xcer.cz/trinity-sb $TDEREPO deps-r14 main-r14" >> /etc/apt/sources.list.d/trinity.list
 		echo "deb-src http://mirror.xcer.cz/trinity-sb $TDEREPO deps-r14 main-r14" >> /etc/apt/sources.list.d/trinity.list
 	elif [ "$SPARKYVERCHECK4" != "" ] || [ "$DEBIANVERCHECK9" != "" ]
 	then
-		$SPARKYXTERM -e "apt-key adv --keyserver keys.gnupg.net --recv-key A04BE668"
+		$SPARKYXTERM "apt-key adv --keyserver keys.gnupg.net --recv-key A04BE668"
 		echo "deb http://mirror.xcer.cz/trinity-sb $TDEREPO deps-r14 main-r14" >> /etc/apt/sources.list.d/trinity.list
 		echo "deb-src http://mirror.xcer.cz/trinity-sb $TDEREPO deps-r14 main-r14" >> /etc/apt/sources.list.d/trinity.list
 	fi	
-	$SPARKYXTERM -e "apt-get update"
-	$SPARKYXTERM -e "apt-get install sparky-desktop-$PACKAGE && apt-get install -f"
-	#$SPARKYXTERM -e "apt-get install -f"
+	$SPARKYXTERM "apt-get update"
+	$SPARKYXTERM "apt-get install sparky-desktop-$PACKAGE"
+	$SPARKYXTERM "apt-get install -f"
 else
-	$SPARKYXTERM -e "apt-get update"
-	$SPARKYXTERM -e "apt-get install --no-install-recommends sparky-desktop-$PACKAGE && apt-get install -f"
-	#$SPARKYXTERM -e "apt-get install -f"
+	$SPARKYXTERM "apt-get update"
+	$SPARKYXTERM "apt-get install --no-install-recommends sparky-desktop-$PACKAGE"
+	$SPARKYXTERM "apt-get install -f"
 fi
 
 # get user name to copy the desktop configs to	
diff --git a/bin/sparky-desktop-del b/bin/sparky-desktop-del
--- a/bin/sparky-desktop-del
+++ b/bin/sparky-desktop-del
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# last update 2018/03/15 by pavroo
+# last update 2018/03/29 by pavroo
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-desktop"
@@ -25,7 +25,6 @@ else
 fi
 
 testroot="`whoami`"
-
 if [ "$testroot" != "root" ]
 then
 	echo "Must be root... Exiting now..."
@@ -41,11 +40,12 @@ OKEXIT="--button=Ok:0 --button=$LOCAL3:1"
 OKBUTTON="--button=Ok:0"
 ARCHARM="`uname -m | grep arm`"
 
-if [ -f /usr/bin/sparky-terminal ]
+if [ -f /usr/bin/sparky-xterm ]
 then
-	SPARKYXTERM="sparky-terminal"
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 $DIALOG $TEXT"\n$LOCAL16" $TITLE"$LOCAL15" $OKEXIT
@@ -209,8 +209,8 @@ then
 	then
 		exit 0
 	else
-		$SPARKYXTERM -e "apt-get purge sparky-desktop-$PACKAGE -y"
-		$SPARKYXTERM -e "apt-get autoremove -f"
+		$SPARKYXTERM "apt-get purge sparky-desktop-$PACKAGE -y"
+		$SPARKYXTERM "apt-get autoremove"
 	fi
 
 elif [ "$PACKAGE" = "lxde" ]
@@ -232,8 +232,8 @@ then
 	then
 		exit 0
 	else
-		$SPARKYXTERM -e "apt-get purge sparky-desktop-$PACKAGE -y"
-		$SPARKYXTERM -e "apt-get autoremove -f"
+		$SPARKYXTERM "apt-get purge sparky-desktop-$PACKAGE -y"
+		$SPARKYXTERM "apt-get autoremove"
 	fi
 
 elif [ "$PACKAGE" = "lxqt" ]
@@ -255,8 +255,8 @@ then
 	then
 		exit 0
 	else
-		$SPARKYXTERM -e "apt-get purge sparky-desktop-$PACKAGE -y"
-		$SPARKYXTERM -e "apt-get autoremove -f"
+		$SPARKYXTERM "apt-get purge sparky-desktop-$PACKAGE -y"
+		$SPARKYXTERM "apt-get autoremove"
 	fi
 
 else
@@ -277,8 +277,8 @@ else
 	then
 		exit 0
 	else
-		$SPARKYXTERM -e "apt-get purge sparky-desktop-$PACKAGE -y"
-		$SPARKYXTERM -e "apt-get autoremove -f"
+		$SPARKYXTERM "apt-get purge sparky-desktop-$PACKAGE -y"
+		$SPARKYXTERM "apt-get autoremove"
 	fi
 
 fi
